package task-002------------.controller;

import org.springframework.web.bind.annotation.*;
import org.springframework.beans.factory.annotation.Autowired;
import task-002------------.service.Task002任务分配后端任务Service;

/**
 * _待填写_
 * Generated by SpecCore execute
 */
@RestController
@RequestMapping("/api/v1")
public class Task002任务分配后端任务Controller {

    @Autowired
    private Task002任务分配后端任务Service task002任务分配后端任务Service;

    // TODO: Add endpoints based on API_CONTRACT.yaml
}
