package task-002------------.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Generated by SpecCore execute
 */
@Repository
public interface Task002任务分配后端任务Repository extends JpaRepository<Task002任务分配后端任务, Long> {

    // TODO: Add custom queries based on TECH.md
}
