package com.example.task003.controller;

import org.springframework.web.bind.annotation.*;
import org.springframework.beans.factory.annotation.Autowired;
import com.example.common.Result;
import com.example.common.BusinessException;
import javax.validation.Valid;
import javax.validation.constraints.*;
import com.example.task003.service.Task003Service;

/**
 * Generated by SpecCore
 * Generated by SpecCore execute
 */
@RestController
@RequestMapping("/api/v1")
public class Task003Controller {

    @Autowired
    private Task003Service task003Service;

    /** 日报 */
    @GetMapping("/api/v1/reports/daily")
    public Result<?> get() {
        throw new BusinessException("Not implemented");
    }

    /** 月报 */
    @GetMapping("/api/v1/reports/monthly")
    public Result<?> get() {
        throw new BusinessException("Not implemented");
    }

    /** 导出报表 */
    @GetMapping("/api/v1/reports/export")
    public Result<?> get() {
        throw new BusinessException("Not implemented");
    }
}
