package com.example.task003.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Generated by SpecCore execute
 */
@Repository
public interface Task003Repository extends JpaRepository<Task003, Long> {

    // TODO: Add custom queries based on TECH.md
}
