package task-001---crud-------.controller;

import org.springframework.web.bind.annotation.*;
import org.springframework.beans.factory.annotation.Autowired;
import task-001---crud-------.service.Task001任务crud后端任务Service;

/**
 * _待填写_
 * Generated by SpecCore execute
 */
@RestController
@RequestMapping("/api/v1")
public class Task001任务crud后端任务Controller {

    @Autowired
    private Task001任务crud后端任务Service task001任务crud后端任务Service;

    // TODO: Add endpoints based on API_CONTRACT.yaml
}
