package com.example.task001.controller;

import org.springframework.web.bind.annotation.*;
import org.springframework.beans.factory.annotation.Autowired;
import com.example.common.Result;
import com.example.common.BusinessException;
import javax.validation.Valid;
import javax.validation.constraints.*;
import com.example.task001.service.Task001Service;

/**
 * Generated by SpecCore
 * Generated by SpecCore execute
 */
@RestController
@RequestMapping("/api/v1")
public class Task001Controller {

    @Autowired
    private Task001Service task001Service;

    /** 创建任务 */
    @PostMapping("/api/v1/tasks")
    public Result<?> create(@RequestBody Object body) {
        throw new BusinessException("Not implemented");
    }

    /** 分页查询 */
    @GetMapping("/api/v1/tasks")
    public Result<?> list(@RequestParam(defaultValue = "1") int page, @RequestParam(defaultValue = "20") int size) {
        throw new BusinessException("Not implemented");
    }

    /** 查询详情 */
    @GetMapping("/api/v1/tasks/{id}")
    public Result<?> getById(@PathVariable Long id) {
        throw new BusinessException("Not implemented");
    }

    /** 更新任务 */
    @PutMapping("/api/v1/tasks/{id}")
    public Result<?> update(@PathVariable Long id, @RequestBody Object body) {
        throw new BusinessException("Not implemented");
    }

    /** 删除任务 */
    @DeleteMapping("/api/v1/tasks/{id}")
    public Result<?> delete(@PathVariable Long id) {
        throw new BusinessException("Not implemented");
    }
}
