package task-001---crud-------.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Generated by SpecCore execute
 */
@Repository
public interface Task001任务crud后端任务Repository extends JpaRepository<Task001任务crud后端任务, Long> {

    // TODO: Add custom queries based on TECH.md
}
