package com.example.task001.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Generated by SpecCore execute
 */
@Repository
public interface Task001Repository extends JpaRepository<Task001, Long> {

    // TODO: Add custom queries based on TECH.md
}
