import { pathExists, readFile, writeFile, ensureDir } from 'fs-extra';
import { join } from 'path';
import { logger, Spinner } from '../utils/logger';
import { getDefaultIteration } from '../core/context';
import { readProjectGraph, scanTasks } from '../core/state';

export interface ReportOptions {
  iteration?: string;
  format?: string;
  output?: string;
  team?: boolean;
  risk?: boolean;
  trend?: boolean;
}

export async function reportCommand(options: ReportOptions): Promise<void> {
  const spinner = new Spinner('Generating project report');
  spinner.start();

  try {
    const iteration = await getDefaultIteration(options.iteration);
    if (!iteration) {
      spinner.fail('No active iteration found. Please specify --iteration or create one first.');
      return;
    }

    const graph = await readProjectGraph(iteration);
    const tasks = graph.tasks.length > 0 ? graph.tasks : await scanTasks(iteration);

    const report = generateReport(iteration, tasks, options);

    if (options.output) {
      await ensureDir(join(options.output, '..'));
      await writeFile(options.output, report);
      spinner.stop(`Report saved to: ${options.output}`);
    } else {
      spinner.stop('Report generated');
      console.log(report);
    }
  } catch (error) {
    spinner.fail(`Report generation failed: ${error}`);
    throw error;
  }
}

function generateReport(iteration: string, tasks: any[], options: ReportOptions): string {
  const total = tasks.length;
  const completed = tasks.filter(t => t.status === 'completed').length;
  const inProgress = tasks.filter(t => t.status === 'in_progress').length;
  const pending = tasks.filter(t => t.status === 'pending').length;
  const completionRate = total > 0 ? Math.round((completed / total) * 100) : 0;

  const format = options.format || 'markdown';

  if (format === 'json') {
    return JSON.stringify({
      iteration,
      generatedAt: new Date().toISOString(),
      summary: { total, completed, inProgress, pending, completionRate },
      tasks: tasks.map(t => ({
        id: t.id,
        name: t.name,
        type: t.type,
        status: t.status,
        assignee: t.assignee
      }))
    }, null, 2);
  }

  if (format === 'html') {
    return generateHtmlReport(iteration, total, completed, inProgress, pending, completionRate, tasks);
  }

  return generateMarkdownReport(iteration, total, completed, inProgress, pending, completionRate, tasks, options);
}

function generateMarkdownReport(
  iteration: string, total: number, completed: number, inProgress: number, pending: number,
  completionRate: number, tasks: any[], options: ReportOptions
): string {
  const lines: string[] = [];
  lines.push(`# Project Report - ${iteration}`);
  lines.push('');
  lines.push(`> Generated at: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`| :--- | :--- |`);
  lines.push(`| Total Tasks | ${total} |`);
  lines.push(`| Completed | ${completed} |`);
  lines.push(`| In Progress | ${inProgress} |`);
  lines.push(`| Pending | ${pending} |`);
  lines.push(`| Completion Rate | ${completionRate}% |`);
  lines.push('');
  lines.push('## Task List');
  lines.push('');
  lines.push(`| Task | Type | Status | Progress | Assignee |`);
  lines.push(`| :--- | :--- | :--- | :--- | :--- |`);
  for (const task of tasks) {
    lines.push(`| ${task.id} | ${task.type} | ${task.status} | ${task.progress}% | ${task.assignee || '-'} |`);
  }
  lines.push('');
  lines.push('---');
  lines.push('Generated by SpecCore CLI');
  return lines.join('\n');
}

function generateHtmlReport(
  iteration: string, total: number, completed: number, inProgress: number, pending: number,
  completionRate: number, tasks: any[]
): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Project Report - ${iteration}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 40px; }
    h1 { color: #333; }
    table { border-collapse: collapse; width: 100%; margin: 20px 0; }
    th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
    th { background: #f5f5f5; }
    .progress { background: #4CAF50; color: white; padding: 4px 8px; border-radius: 4px; }
  </style>
</head>
<body>
  <h1>Project Report - ${iteration}</h1>
  <p>Generated at: ${new Date().toISOString()}</p>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Total Tasks</td><td>${total}</td></tr>
    <tr><td>Completed</td><td>${completed}</td></tr>
    <tr><td>In Progress</td><td>${inProgress}</td></tr>
    <tr><td>Pending</td><td>${pending}</td></tr>
    <tr><td>Completion Rate</td><td><span class="progress">${completionRate}%</span></td></tr>
  </table>
  <h2>Task List</h2>
  <table>
    <tr><th>Task</th><th>Type</th><th>Status</th><th>Progress</th><th>Assignee</th></tr>
    ${tasks.map(t => `<tr><td>${t.id}</td><td>${t.type}</td><td>${t.status}</td><td>${t.progress}%</td><td>${t.assignee || '-'}</td></tr>`).join('')}
  </table>
</body>
</html>`;
}
