package task-003------------.controller;

import org.springframework.web.bind.annotation.*;
import org.springframework.beans.factory.annotation.Autowired;
import task-003------------.service.Task003任务筛选后端任务Service;

/**
 * _待填写_
 * Generated by SpecCore execute
 */
@RestController
@RequestMapping("/api/v1")
public class Task003任务筛选后端任务Controller {

    @Autowired
    private Task003任务筛选后端任务Service task003任务筛选后端任务Service;

    // TODO: Add endpoints based on API_CONTRACT.yaml
}
