package task-003------------.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Generated by SpecCore execute
 */
@Repository
public interface Task003任务筛选后端任务Repository extends JpaRepository<Task003任务筛选后端任务, Long> {

    // TODO: Add custom queries based on TECH.md
}
