package com.example.task002.controller;

import org.springframework.web.bind.annotation.*;
import org.springframework.beans.factory.annotation.Autowired;
import com.example.common.Result;
import com.example.common.BusinessException;
import javax.validation.Valid;
import javax.validation.constraints.*;
import com.example.task002.service.Task002Service;

/**
 * Generated by SpecCore
 * Generated by SpecCore execute
 */
@RestController
@RequestMapping("/api/v1")
public class Task002Controller {

    @Autowired
    private Task002Service task002Service;

    /** 用户登录 */
    @PostMapping("/api/v1/auth/login")
    public Result<?> create(@RequestBody Object body) {
        throw new BusinessException("Not implemented");
    }

    /** 用户注册 */
    @PostMapping("/api/v1/auth/register")
    public Result<?> create(@RequestBody Object body) {
        throw new BusinessException("Not implemented");
    }

    /** 当前用户信息 */
    @GetMapping("/api/v1/auth/me")
    public Result<?> get() {
        throw new BusinessException("Not implemented");
    }
}
